### ISSUE TITLE
Option to have manual control of basestations

### ISSUE THREAD

**Issue by LayyLo** [monstermac77/mixed-vr#6]
In use cases such as using Vive FBT in a MixedVR setup, users may not always want to be using basestations every time they use SteamVR, occasionally using SteamVR only with their headset - for example, for non FBT games.

Here, it would be useful to not have the basestations turn on instantly when you load into SteamVR, but have something like an opt-in choice of a pop-up just after SteamVR loads, that asks whether you need the basestations on at this time. This could be something you could choose to have in the config, for example.

Additionally, it would be really useful to have access to this pop-up manually, so if you are using SteamVR without basestations, and half way through your play session, you need them on, you can just access basestation control from your desktop.

**Comment by LayyLo** [comment]
I am not sure if, as I am not a contributor, I can assign a label to this. The label should be -enhancement- though I have no option to add this

**Comment by monstermac77** [comment]
> I am not sure if, as I am not a contributor, I can assign a label to this. The label should be -enhancement- though I have no option to add this

Just added the enhancement label, thanks!

**Comment by monstermac77** [comment]
This has been resolved with #9, which I've just included in [v1.4](https://github.com/monstermac77/vr/releases/tag/v1.4)!
