### ISSUE TITLE
Allow selective suppression of the User Access Control (UAC) dialog for USBDeview.exe 

### ISSUE THREAD

**Issue by monstermac77** [monstermac77/mixed-vr#7]
Every time MixedVR Manager goes through its startup/shutdown procedure it uses USBDeview, which requires being run as administrator, to enable/disable the HMD. Out of the box without completing any prerequisites, this will cause a dialog that says "Do you want to allow this app to make changes to your device?". Obviously, we want to suppress this dialog to eliminate all required user interaction. 

Our current suggested way is just to disable all of these notifications by opening the "User Account Control Settings" and setting it to "Never Notify". However, many users will likely want to preserve these notifications for other apps they may not trust as much. 

Previously, we said the following in the prerequisites: 
> If doing this makes you uncomfortable, [whitelist](https://lifehacker.com/how-to-eliminate-uac-prompts-for-specific-applications-493128966) just USBDeview and modify `usbDeviewPath` in `config.bat`

The `usbDeviewPath` code was graciously contributed by @timberrr, who was using this configuration. But my originally suggested UAC workaround simply doesn't work, as you can see from [this user's experience with v1.3.1](https://www.reddit.com/r/HPReverb/comments/ku0c2e/my_experience_with_setting_up_an_hp_reverb_g2/giz60aa/?context=3). The crux of the issue is that Task Scheduler doesn't allow for dynamic arguments to be passed. When we try to pass dynamic arguments, we get "ERROR: Invalid argument/option - ... Type "SCHTASKS /RUN /?" for usage." I was not able to figure this out. Short of copying a lot of the functionality into a separate `.bat` file that is run and essentially determines the value of the arguments (as suggested [here](https://superuser.com/q/1210539/699131)), it may not be possible. It would be great if someone could confirm this or show how it is possible. 

In a completely different way of solving this problem, I thought maybe we could use the Task Scheduler method used above to actually launch MixedVR Manager itself. Since it would have been granted administrator privileges, it would be able to launch USBDeview.exe as administrator without triggering a UAC dialog (I have tested this). This would be even better, because it would require less configuration for the user (no modification to paths in the `config.bat`). However, I couldn't get Task Scheduler to launch a `.vbs` script, which is needed to get MixedVR Manager launched in the background (i.e. without a terminal window). I think this should be possible, though. 

Lastly, whatever solution we go with/discover, I think we should make the setup easier for users and less error prone, by providing them with the exact command they can run in the command prompt to create the Task Scheduler task, which would look like `SCHTASKS /CREATE /TN "MixedVRTasks" /TR....`, and a pre-built `.lnk` shortcut if possible. That way they don't have to do anything in a GUI, if they don't want to.

**Comment by timberrr** [comment]
One (very ugly) option for the task scheduler would be a bat file just with:
`cscript.exe mixedvr-manager-launcher.vbs`
and that's what is created as the scheduled task. It would probably at that stage make sense for the runtime bat and vbs script to go into the /bin folder too just for housekeeping and ease of use?

**Comment by timberrr** [comment]
So I've created an "install" script (and a very rudimentary uninstall script) that should create an elevated scheduled task on logon to run a bat file that will then run the vbs to launch the runtime as a background process...

It's on my fork here: https://github.com/timberrr/vr/

Didn't want to do a pull request until you've had a look and checked if it works for you? The install and uninstall scripts should be run as admin just via right click > run as administrator.

I've also moved the startup bat, runtime and vbs into the /bin folder so that the only the config and install scripts are in the base, just to keep it tidy

**Comment by timberrr** [comment]
Hmm I seem to be hitting a roadblock with the script not executing. As far as I can see the files are all firing, including the VBS, but the VBS doesn't launch the runtime bat

*Edit*
Aha - the VBS is picking up Windows\System32 as it's working directory so isn't finding the bat. I shall keep trying!

*Edit*
OK I might have vastly over-complicated this, but - I think it's working now. The bat files pass the folder location of the scripts to the vbs as an argument, and the vbs now takes this to locate the bat file to launch. It does it optionally so you can also still run the vbs directly

**Comment by monstermac77** [comment]
To keep this thread updated: @timberrr created #8 to address this issue. However, some improvements will be made and presumably a subsequent pull request will end up closing this issue.

**Comment by monstermac77** [comment]
Fantastic work by @timberrr in #9, closing this issue.
